services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    ports: 
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      retries: 5
    networks:
      - mynetwork
  
  kafka:
    image: ubuntu/kafka
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports: 
      - "9092:9092"
    environment:
        KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
        KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
        KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - mynetwork

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - mynetwork
  
  migrations:
    build: ./migrations
    container_name: migrations
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - mynetwork
  
  producer:
    build: ./producer
    container_name: producer
    ports:
     - "8080:8080"
    depends_on:
      migrations:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    networks:
      - mynetwork

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      producer:
        condition: service_started
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge